**ChatGPT is forbidden**

**Data generation**

Create and visualize arrays containing only real numbers, then integers, then strings, then a mix of integers and strings

In [1]:
pip install numpy

     ---------------------------------------- 15.8/15.8 MB 7.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Programs Files\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [11]:
import numpy as np
sample_length = 10
values = np.random.randint(low=10000, high= 15000, size = sample_length)
columns = []
for i in values:
     columns.append('q' + str(i))

Add two arrays made of integers, element by element (the two arrays must be the same size)

In [10]:
array_1 = np.array([1,1,4,5])
array_2 = np.array([1,3,4])

out = (array_1+array_2[:,None]).ravel()

Create a 3*3 array including only zeros on the first line, then 1s on the second line, then the number 5 on the third line

In [9]:
my_array = np.zeros((3, 3))
my_array[1, :] = 1
my_array[2, :] = 5

print(my_array)

[[0. 0. 0.]
 [1. 1. 1.]
 [5. 5. 5.]]


Extract the shape attribute from this array

In [8]:
print('shape of array :', my_array.shape)

shape of array : (3, 3, 3)


Create an array of 3 by 3 by 3 including only real numbers chosen from a normal distribution

In [7]:
my_array = np.random.normal(size=(3, 3, 3))
print(my_array)

[[[ 0.34648948  0.94286185  0.93356474]
  [ 1.08928308 -0.52639637  0.61874298]
  [-0.21805356  0.83280708 -0.65217301]]

 [[ 0.43043317  0.82631689  0.05255127]
  [-0.5608492   0.67982937  0.01651576]
  [-0.45699924  0.08363165 -1.47434547]]

 [[ 0.04935381  1.49091968  0.92305947]
  [-0.37236563 -0.5316894  -0.10562447]
  [-1.15047949  0.11763102  0.19666202]]]


Create a vector comprising 7 equally spaced values, between 2 and 3

In [3]:
vector = np.linspace(2, 3, 7)
print(vector)


[2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.        ]


Use the choice function to sample 5 values ​​from this last vector, once with replacement, and once without replacement

In [6]:

sample_with_replacement = np.random.choice(vector, size=5, replace=True)
print("Sample with replacement:", sample_with_replacement)


sample_without_replacement = np.random.choice(vector, size=5, replace=False)
print("Sample without replacement:", sample_without_replacement)


Sample with replacement: [13 18 16 15 16]
Sample without replacement: [16 19 13 18 15]


Create a vector corresponding to a sequence of numbers, from 13 to 19, counting in steps of one

In [4]:
vector = [x for x in range(13, 20)]
print(vector)


[13, 14, 15, 16, 17, 18, 19]


Create a 5*5 identity matrix

In [13]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create a 5*5 matrix of zeros, with 1 on the diagonal. Then specifically extract this diagonal

In [15]:
diag=np.diag(a)
print(diag)

[1. 1. 1. 1. 1.]


Complete this NumPy line to determine if the elements of a vector are finite (not infinite or not
a number)

In [16]:
a = np.array([1, 0, np.nan, np.inf]) 
print(np.isfinite(a))

[ True  True False False]


Complete this NumPy program to test element by element if it corresponds to infinity (positive
or negative)

In [17]:
b=np.array([1, 0, np.nan, np.inf])
print(np.isinf(b))

[False False False  True]


Complete this NumPy program to perform a comparison by element (equal, then equal to
a certain tolerance) of two given tables

In [18]:
x = np.array([72, 79, -135, 120, -10, 60, 100])
y = np.array([72, 79, -135, 120, -10, 60, 100.01])
print(np.equal(x, y))

[ True  True  True  True  True  True False]


**Subsetting & reshaping**

Create an array of 7 by 7 including only real numbers chosen from a normal distribution, then select only the first row, the first column, all columns up to the third, and the element of the second column and third row

In [19]:

array = np.random.randn(7, 7)

first_row = array[0, :]

first_column = array[:, 0]

up_to_third_column = array[:, :3]

element_2nd_col_3rd_row = array[2, 1]  

print("First Row:", first_row)
print("First Column:", first_column)
print("All Columns Up to Third:", up_to_third_column)
print("Element in Second Column and Third Row:", element_2nd_col_3rd_row)


First Row: [-0.35166985  0.20783924  0.01416339  1.40345433 -1.90778497 -1.88005888
  0.13130251]
First Column: [-0.35166985  0.62583058 -0.32588754 -1.45309205 -1.718128   -0.27956276
  0.25964816]
All Columns Up to Third: [[-0.35166985  0.20783924  0.01416339]
 [ 0.62583058 -0.34456531  0.12296315]
 [-0.32588754 -0.56732195  0.1221385 ]
 [-1.45309205 -0.55668322 -2.134473  ]
 [-1.718128   -0.197047   -1.21125508]
 [-0.27956276 -0.87138342 -0.3528687 ]
 [ 0.25964816  2.06009819  1.02017186]]
Element in Second Column and Third Row: -0.567321949817992


Create an array that is the repetition of one 1, two 2s, and three 3s, then from this vector, create a new array including the "unique" values ​​(i.e., 1, 2, and 3)

In [20]:

arr = np.repeat([1, 2, 3], [1, 2, 3])
unique_values = np.unique(arr)

print("Original array with repetitions:", arr)
print("Unique values:", unique_values)


Original array with repetitions: [1 2 2 3 3 3]
Unique values: [1 2 3]


Créez un array de 5*5 comprenant des chiffres entiers choisis aléatoirement, puis réalisez une transposition de cette matrice

In [21]:

random_array = np.random.randint(0, 10, (5, 5))

print("Original Array:")
print(random_array)

transposed_array = np.transpose(random_array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[6 6 9 1 7]
 [9 4 4 8 6]
 [4 2 8 5 7]
 [6 0 1 9 8]
 [8 1 9 0 5]]

Transposed Array:
[[6 9 4 6 8]
 [6 4 2 0 1]
 [9 4 8 1 9]
 [1 8 5 9 0]
 [7 6 7 8 5]]


Create a vector of 25 successive integers, then use reshape to make it a 5*5 matrix. Then play with the reshape function to illustrate how it works

In [31]:
vector = np.arange(25)
reshapee=vector.reshape(5,5)
print(reshapee)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Make a broadcast of two arrays of your design

In [32]:

a = np.array([17, 11, 19])
print(a)
b = 3
print(b)


c = a + b 
print(c)


[17 11 19]
3
[20 14 22]


Illustrate “type casting” by changing the data type contained in an array of your choice

In [ ]:

original_array = np.array([1, 2, 3, 4, 5])

print("Original Array Data Type:", original_array.dtype)

float_array = original_array.astype(np.float64)

print("Float Array Data Type:", float_array.dtype)


Create a 4*4 array including integers, which you will cut in half using vsplit

In [ ]:

array_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])

half1, half2 = np.vsplit(array_4x4, 2)


Create a 4*4 array of integers, which you "unfold" into a 1D vector using the reshape command. You will then use the shuffle and permutation commands to mix these numbers

In [ ]:

array_4x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16]])

vector = array_4x4.reshape(-1)


np.random.shuffle(vector)

permuted_indices = np.random.permutation(len(vector))
permuted_vector = vector[permuted_indices]


Merge a 3*3 matrix made of integers, with a vector of three elements, once horizontally, and once vertically

In [ ]:

matrix_3x3 = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])


vector = np.array([10, 11, 12])

merged_horizontal = np.hstack((matrix_3x3, vector.reshape(-1, 1)))

merged_vertical = np.vstack((matrix_3x3, vector))


Demonstrate your mastery and understanding of the resize command, then the argsort command. Make comments

In [ ]:

initial_array = np.array([4, 2, 7, 1, 9])

resized_array = np.resize(initial_array, (3, 3))


print("Resized Array:")
print(resized_array)


sorted_indices = np.argsort(initial_array)


print("\nSorted Indices:")
print(sorted_indices)


Write a NumPy program to get the n largest values ​​of an array, use np.partition and play with both positive and negative values ​​of n, the second argument of the function, before explaining in your words what is happening. pass

In [ ]:

arr = np.array([3, 1, 8, 4, 7, 2, 9, 6, 5])

n_positive = 3
largest_values_pos = arr[np.argpartition(-arr, n_positive)[:n_positive]]

n_negative = -3
largest_values_neg = arr[np.argpartition(arr, n_negative)[:n_negative]]

print(f"Array: {arr}")
print(f"n = {n_positive}, Largest Values: {largest_values_pos}")
print(f"n = {n_negative}, Largest Values: {largest_values_neg}")


Sort a 2*2 array, on the one hand before having flattened it, and on the other hand after having flattened it

In [4]:

array_2x2 = np.array([[4, 2],
                       [3, 1]])

sorted_before_flatten = np.sort(array_2x2, axis=None)

flattened_array = array_2x2.flatten()
sorted_after_flatten = np.sort(flattened_array)

print("Sorted 2x2 array before flattening:")
print(sorted_before_flatten)

print("\nSorted flattened array:")
print(sorted_after_flatten)


Produce a 1D array of the size of your choice, containing a random number of 2 between 5 and 10. Count the number of times the value 2 is repeated in the array.

In [ ]:

array_size = np.random.randint(5, 11)

random_array = np.random.randint(0, 4, array_size)


num_twos = np.random.randint(1, array_size)  
random_indices = np.random.choice(range(array_size), num_twos, replace=False)
random_array[random_indices] = 2

count_twos = np.count_nonzero(random_array == 2)

print("Generated Array:", random_array)
print("Number of times the value 2 is repeated:", count_twos)


Create an integer vector of size 30 with numbers between 1 and 12. Then use np.isin to check if the numbers 4, 6 and 7 appeared in the sequence

In [ ]:


integer_vector = np.random.randint(1, 13, 30)
check_numbers = np.isin([4, 6, 7], integer_vector)
print(check_numbers)


**np.where**

Create an integer vector of size 30 with numbers between 1 and 12, then use the np.where function to identify indexes of numbers greater than 6

In [ ]:

integer_vector = np.random.randint(1, 13, 30)
indexes_greater_than_6 = np.where(integer_vector > 6)
print(indexes_greater_than_6)


**Données manquantes**

Create an array of 3 * 3 and introduce a missing value at index [0,0], via np.nan

In [ ]:


array_3x3 = np.array([[np.nan, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])


Transform this missing value into zero using np.fillna

In [ ]:


array_3x3 = np.array([[np.nan, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

array_3x3 = np.nan_to_num(array_3x3, nan=0)


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the union of these two sets and return the result.

In [ ]:

A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}


union_result = A.union(B)

print("Union of sets A and B:", union_result)


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using the appropriate function to find the intersection of these two sets and return the result

In [ ]:
A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}

intersection_result = A.intersection(B)

print(intersection_result)


You have a set of integer values ​​= {2, 4, 6}, and a NumPy array = [1, 2, 3, 4, 5]. Write a program in Python using np.in1d ​​to check if each element in array belongs to the set values. The program must return an array of booleans indicating the membership of each element

In [ ]:

set_values = {2, 4, 6}
array_values = np.array([1, 2, 3, 4, 5])

membership_result = np.in1d(array_values, list(set_values))

print(membership_result)


You have two sets of integers: A = {1, 2, 3, 4, 5} and B = {3, 4, 5, 6, 7}. Write a program in Python using np.setdiff1d to find elements that are in A but not in B, then return the result.

In [ ]:

A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}


result = np.setdiff1d(np.array(list(A)), np.array(list(B)))

print(result)


Write a function that takes a NumPy array as input and returns a new array containing the differences between consecutive elements of the input array. For example, if the input is [1, 3, 7, 11], the result should be [2, 4, 4].

In [ ]:

def consecutive_differences(arr):
    return np.diff(arr)

# Example usage:
input_array = np.array([1, 3, 7, 11])
result = consecutive_differences(input_array)
print(result)


**Calculus with NumPy**

Create a matrix of 4*4 real numbers, both negative and positive, then calculate for each row the sum, average, and cumulative sum

In [ ]:
import numpy as np

# Creating a 4x4 matrix of real numbers
matrix_4x4 = np.array([[1.5, -2.2, 3.1, -4.5],
                       [2.0, -3.0, 4.0, -5.0],
                       [-1.1, 2.2, -3.3, 4.4],
                       [1.0, -2.0, 3.0, -4.0]])

# Calculating sum, average, and cumulative sum for each row
sum_per_row = np.sum(matrix_4x4, axis=1)
average_per_row = np.mean(matrix_4x4, axis=1)
cumulative_sum_per_row = np.cumsum(matrix_4x4, axis=1)

print("Sum per row:")
print(sum_per_row)
print("\nAverage per row:")
print(average_per_row)
print("\nCumulative sum per row:")
print(cumulative_sum_per_row)


Repeat the previous operation by averaging the absolute values ​​of the numbers, then the minimum value and the maximum value; you will finally create a last column using the maximum value with the np.round function

In [ ]:
import numpy as np

# Creating a 4x4 matrix of real numbers
matrix_4x4 = np.array([[1.5, -2.2, 3.1, -4.5],
                       [2.0, -3.0, 4.0, -5.0],
                       [-1.1, 2.2, -3.3, 4.4],
                       [1.0, -2.0, 3.0, -4.0]])

# Averaging absolute values of numbers for each row
average_abs_values = np.mean(np.abs(matrix_4x4), axis=1)

# Finding minimum and maximum values for each row
min_values = np.min(matrix_4x4, axis=1)
max_values = np.max(matrix_4x4, axis=1)

# Creating a new column using the maximum value rounded to the nearest integer
rounded_max_value = np.round(max_values, 0)
matrix_with_new_column = np.column_stack((matrix_4x4, rounded_max_value))

print("Average of absolute values per row:")
print(average_abs_values)
print("\nMinimum values per row:")
print(min_values)
print("\nMaximum values per row:")
print(max_values)
print("\nMatrix with new rounded max column:")
print(matrix_with_new_column)


Place 10 points randomly on a plane, then calculate the distance vectors between these different points. How many distance calculations do you do? Visualize points with matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generating 10 random points on a plane
num_points = 10
x_coords = np.random.rand(num_points)
y_coords = np.random.rand(num_points)

# Calculating distance vectors between points
points = np.column_stack((x_coords, y_coords))
distances = np.zeros((num_points, num_points))
for i in range(num_points):
    for j in range(num_points):
        distances[i, j] = np.linalg.norm(points[i] - points[j])

# Counting distance calculations
num_distance_calculations = num_points * (num_points - 1) // 2

# Visualizing points
plt.scatter(x_coords, y_coords, color='blue')
plt.title('Randomly Placed Points on a Plane')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

print(f"Number of distance calculations: {num_distance_calculations}")


Now visualize these distances on the plan, still with matplotlib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Generating 10 random points on a plane
num_points = 10
x_coords = np.random.rand(num_points)
y_coords = np.random.rand(num_points)

# Calculating distance vectors between points
points = np.column_stack((x_coords, y_coords))
distances = np.zeros((num_points, num_points))
for i in range(num_points):
    for j in range(num_points):
        distances[i, j] = np.linalg.norm(points[i] - points[j])

# Visualizing points and their connections based on distances
plt.scatter(x_coords, y_coords, color='blue')
for i in range(num_points):
    for j in range(i+1, num_points):
        plt.plot([x_coords[i], x_coords[j]], [y_coords[i], y_coords[j]], color='black', alpha=0.5)

plt.title('Distances between Randomly Placed Points on a Plane')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()


Create a list of randomly generated integers, and use np.mod (for modulo) to identify indexes of even numbers

In [ ]:
import numpy as np

# Generating a list of randomly generated integers
random_integers = np.random.randint(1, 100, 20)

# Identifying indexes of even numbers using np.mod
even_indexes = np.where(np.mod(random_integers, 2) == 0)

print("Randomly generated integers:", random_integers)
print("Indexes of even numbers:", even_indexes)


**Fonctions universelles**

Take the vector {3,4,6,9} and use the add and multiply functions

In [ ]:
import numpy as np

vector = np.array([3, 4, 6, 9])

# Adding 5 to each element of the vector
add_result = np.add(vector, 5)

# Multiplying each element of the vector by 2
multiply_result = np.multiply(vector, 2)

print("Vector:", vector)
print("Vector after adding 5 to each element:", add_result)
print("Vector after multiplying each element by 2:", multiply_result)


Use multiply.outer on two vectors, and explain the nature of the corresponding operations

In [ ]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Compute the outer product using multiply.outer
outer_product = np.multiply.outer(vector1, vector2)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("\nOuter Product:")
print(outer_product)


Apply the negative function to the array [2,3,5]

In [ ]:
import numpy as np

# Define an array
array = np.array([2, 3, 5])

# Applying the negative function to the array
negated_array = np.negative(array)

print("Original Array:", array)
print("Array after applying negative function:", negated_array)


**Numpy and strings**

Merge two arrays each comprising two strings, using the np.char.add function

In [ ]:
import numpy as np

# Define two arrays with strings
array1 = np.array(['Hello ', 'World'])
array2 = np.array(['Open', 'AI'])

# Merge the arrays using np.char.add
merged_array = np.char.add(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Merged Array:", merged_array)


Use the np.char.join function to insert the symbol ";" into a 5-character string. between each letter

Use the np.char.upper function on the character string of your choice

Use np.char.replace to demonstrate how to replace one string (in a sentence) with another

Use np.char.split to split an array containing two sentences into as many elements as there are words in them

Create an array containing three strings including a repeated pattern, common to the three elements. Use np.char.count to count the number of times this pattern is repeated

Modify an array of length 5 by inserting elements, then removing some

Write a NumPy program to add a border (padded with 0s) around an existing array. You need two layers of zeros all around

Write a NumPy program to create a 5x5 array with random values ​​and normalize it by row

**Pour aller plus loin que la simple maîtrise des fonctions Numpy** (ChatGPT interdit)

Nous vous proposons quelques exercices de programmation, pour aller au-delà de la simple connaissance de fonctions

*Exercice 1*

Si le produit de deux nombres entiers est égal ou inférieur à 1 000, renvoyez le produit ; sinon, renvoyez leur somme. Nous attendons de vous que vous construisiez une fonction. numéro1 = 20,
nombre2 = 30, la sortie est 600

*Exercice 2*

Créez un programme qui invite l'utilisateur à saisir une chaîne, puis affiche
les caractères situés à des positions d'index paires. Par exemple, si la chaîne est
"exemple", le programme doit afficher les caractères "x", "m", "l".

*Exercice 3*

Créez un programme qui prend une chaîne en entrée et supprime les caractères de
le début de la chaîne jusqu'à un index spécifié, ce qui donne une nouvelle chaîne.
Par exemple, si nous appelons la fonction remove chars(”example”, 3), la sortie
devrait être « mple ». Notez que l'index spécifié, noté 'n', doit être inférieur à la longueur de
la chaîne.

*Exercice 4*

Itérer la liste de nombres donnée et imprimer uniquement les nombres divisibles
par 5:  la liste donnée est [10, 20, 33, 46, 55] Divisible par 5 : 10, 20, 55

*Exercice 5*

Développer un programme qui détermine le nombre d'occurrences de la sous-chaîne
"Emma" dans une chaîne donnée.
• Donné : « Emma est une bonne développeuse. Emma est institutrice. »
• Résultat attendu : Emma est apparue 2 fois
Faites-le une fois avec la méthode « count » de chaîne, une fois sans.

*Exercice 6*

Écrivez un programme pour vérifier si le nombre donné est un nombre palindrome.
Un nombre palindrome est un nombre qui est le même après l'inverse. Par exemple
545, ce sont les nombres palindromes
Production attendue:
• numéro original 121 : Oui. le nombre donné est le numéro du palindrome
• numéro d'origine 125 : le numéro donné n'est pas un numéro palindrome

*Exercice 7*

Écrivez une boucle while pour afficher chaque caractère d'une chaîne et, si un caractère est
numéro : arrêter la boucle.